### ISSUE TITLE
[FIX] Comment 순환참조 해결

### ISSUE THREAD

**Issue by ywj9811** [KUSITMS-27-chilling/Encore-BE#100]
## Description
Comment 부분 순환 참조 해결

## Todo

- [x] 오류 부분 해석
- [x] 순환 참조 해결
- [x] 댓글 부분 수정
- [x] 리뷰 댓글 완료

**Comment by ywj9811** [comment]
"cascade = CascadeType.ALL, orphanRemoval = true" 이거 삭제했어
무결성에서 좋기는 하지만, 부모 댓글이 삭제되었을 때 아래 대댓글이 모두 삭제되는게 맞는 방식인지는 모르겠어서 여기서는 안쓰는게 좋을거같아
