### ISSUE TITLE
[FEAT] 우동강

### ISSUE THREAD

**Issue by ywj9811** [KUSITMS-27-chilling/Encore-BE#103]
## Description
우동강 진행

## Todo

- [x] 우동강 임시 ERD 생성
- [x] 우동강 기본 설계
- [x] 우동강 조회 구현

## Etc
우동강 확장 가능성 생각
